<?php
/**
 * 所有模块公用配置，由后台《系统设置》生成
 * @author zhang qing <490702087@qq.com>
 * @since  2016-10-12 12:04:32
 */
return array (
  'SITE_NAME' => '企业网站系统',
  'SITE_TITLE' => '你是他的',
  'SITE_KEYWORDS' => '企业MVC框架',
  'SITE_DESCRIPTION' => '简单实用就好~',
  'DB_TYPE' => 'mysql',
  'DB_HOST' => 'localhost',
  'DB_PORT' => '3306',
  'DB_USER' => 'root',
  'DB_PWD' => 'pw2020',
  'DB_NAME' => 'frame',
  'DB_PREFIX' => 'fm_',
  'DB_CHARSET' => 'utf8',
  'TMPL_TEMPLATE_CHARSET' => 'UTF-8',
  'TMPL_TEMPLATE_SUFFIX' => '.twig',
  'TMPL_TEMPLATE_CACHE' => false,
  'DEFAULT_TIMEZONE' => 'PRC',
  'DEFAULT_MODULE' => 'home',
  'DEFAULT_C_LAYER' => 'controller',
  'DEFAULT_M_LAYER' => 'model',
  'DEFAULT_V_LAYER' => 'view',
  'DEFAULT_CONTROLLER' => 'index',
  'DEFAULT_ACTION' => 'index',
  'DEFAULT_AJAX_RETURN' => 'JSON',
  'DEFAULT_JSONP_HANDLER' => 'jsonpReturn',
  'VAR_JSONP_HANDLER' => 'callback',
  'DEFAULT_FILTER' => 'htmlspecialchars|trim',
  'VAR_AUTO_STRING' => false,
  'VAR_PATHINFO' => 's',
  'URL_HTML_SUFFIX' => '.html',
  'UPLOAD_IMAGE_EXT' => 'bmp|png|jpeg|gif|jpg',
  'UPLOAD_IMAGE_MAXSIZE' => '1024',
  'UPLOAD_IMAGE_FOLDER' => 'upload/image/',
  'UPLOAD_FILE_EXT' => 'png|jpg|jpeg|gif|bmp|flv|swf|mkv|avi|rm|rmvb|mpeg|mpg|ogg|ogv|mov|wmv|mp4|webm|mp3|wav|mid|rar|zip|tar|gz|7z|bz2|cab|iso|doc|docx|xls|xlsx|ppt|pptx|pdf|txt|md|xml',
  'UPLOAD_FILE_MAXSIZE' => '5120',
  'UPLOAD_FILE_FOLDER' => 'upload/file/',
  'UPLOAD_VIDEO_EXT' => 'flv|swf|mkv|avi|rm|rmvb|mpeg|mpg|ogg|ogv|mov|wmv|mp4|webm|mp3|wav|mid',
  'UPLOAD_VIDEO_MAXSIZE' => '5120',
  'UPLOAD_VIDEO_FOLDER' => 'upload/video/',
  'UPLOAD_SCRAWL_EXT' => 'png',
  'UPLOAD_SCRAWL_MAXSIZE' => '1024',
  'UPLOAD_SCRAWL_FOLDER' => 'upload/scrawl/',
  'UPLOAD_SNAPSCREEN_EXT' => 'jpg',
  'UPLOAD_SNAPSCREEN_MAXSIZE' => '1024',
  'UPLOAD_SNAPSCREEN_FOLDER' => 'upload/snapscreen/',
  'MAIL_SMTP_HOST' => 'smtp.qq.com',
  'MAIL_SMTP_PORT' => '25',
  'MAIL_SMTP_USERNAME' => '49****087@qq.com',
  'MAIL_SMTP_PASSWORD' => 'qwervnb',
  'MAIL_SMTP_SMTPSECURE' => '',
);